name: Inspect bot

on:
  push:
    branches: [ "main", "debug-workflow" ]
    paths: ["**.cs"]
  pull_request:
    branches: [ "main" ]
    paths: ["**.cs"]

defaults:
 run:
  working-directory: ./Bot

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore
      run: dotnet restore
    - name: Inspect
      uses: muno92/resharper_inspectcode@v1
      with:
        workingDirectory: './Bot'
        solutionPath: './Bot.sln'
        noBuild: true
        exclude: '**'
        include: '**.cs'
