name: relation.py
on:
  push:
    paths:
      - 'relation/relation.py'
  pull_request:
    paths:
      - 'relation/relation.py'

jobs:      
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Check if graph is updated
        uses: tj-actions/changed-files@v35
        id: filter
        with:
          files: 'relation/Figure_1.png'
      - name: Install fonts
        run: sudo apt-get install ttf-wqy-microhei 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install networkx matplotlib scipy
      - name: Generate graph
        run: |
          cd relation
          python relation.py save
      - name: Upload graph
        if: steps.filter.outputs.any_changed == 'false'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto generate relation graph by Workflow
