name: relation.py
on:
  push:
    paths:
      - 'relation/relation.py'
  pull_request:
    paths:
      - 'relation/relation.py'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      graph: ${{steps.filter.outputs.graph}}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            graph:
              - 'relation/Figure_1.png'
  draw:
    runs-on: ubuntu-latest
    needs: [verify, check-graph]
    if: needs.paths-filter.outputs.graph == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install networkx
      - name: Generate graph
        run: |
          cd relation
          python relation.py save